## You should change each of the following fields
## to customize your blog

title: "The Data Ocean"
description: "Learn to Navigate the Waves of Information" 
author: Carter Hale
author_description: "Hi! My name is Carter and I'm a senior at BYU, where I study Statistics with an emphasis in Data Science and minor in Math. When I'm not staring at a computer wondering why my code isn't working, I enjoy playing volleyball, reading, and judging cooking shows wayyyy too harshly for my skill level!" 

url: https://chale15.github.io
baseurl: data-science-blog ## change this to the name of your blog repository
header_image: /assets/img/header_image.png ## change header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: chale15
    twitter: 
    facebook: 
    email: chale15@byu.edu
    linkedin: carterhale15
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




